import { db } from "./db";
import { eq, and, desc, asc, sql, ilike, or, inArray } from "drizzle-orm";
import type {
  Client,
  InsertClient,
  Opportunity,
  InsertOpportunity,
  Campaign,
  InsertCampaign,
  Template,
  InsertTemplate,
  User,
  UpsertUser,
  Interaction,
  InsertInteraction,
  Contact,
  InsertContact,
  CustomField,
  InsertCustomField,
  AuditLog,
  InsertAuditLog,
  ImportJob,
  InsertImportJob,
  Conversation,
  InsertConversation,
  Message,
  InsertMessage,
  QuickReply,
  InsertQuickReply,
  ClientNote,
  InsertClientNote,
  Tag,
  InsertTag,
} from "@shared/schema";
import {
  clients,
  opportunities,
  campaigns,
  templates,
  users,
  interactions,
  contacts,
  customFields,
  auditLogs,
  importJobs,
  whatsappSessions,
  conversations,
  messages,
  quickReplies,
  clientNotes,
  tags,
} from "@shared/schema";